# Generated by Django 5.2.7 on 2025-10-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
    ]
