# Generated by Django 5.2.7 on 2025-10-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jugador_partido'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jugador',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='partido',
            name='jugador1',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='jugador2',
        ),
        migrations.AddField(
            model_name='jugador',
            name='dorsal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.torneo')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='core.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_equipo1', to='core.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_equipo2', to='core.equipo'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('equipo', 'nombre'), name='unique_jugador_en_equipo'),
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='torneo',
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('torneo', 'nombre'), name='unique_equipo_en_torneo'),
        ),
    ]
